apiVersion: v1
kind: Service
metadata:
  name: {{ include "oidc-kubeconfig-service.fullname" . }}
  labels:
{{ include "oidc-kubeconfig-service.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "oidc-kubeconfig-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
